### ISSUE TITLE
use of '_' as an identifier might not be supported in releases after Java SE 8

### ISSUE THREAD

**Issue by debdattabasu** [javadev/underscore-java#1]
Hi, 
First of all, thank you for such an awesome library, made even more awesome by Java8's lambdas.  However, in Java8 builds, the use of underscore seems to be marked for deprecation. It gives a warning on compilation. Is there some other name you can give the underscore object?  

Regards,
Debdatta Basu

**Comment by javadev** [comment]
What character may be used for replacement _? :)

**Comment by debdattabasu** [comment]
Well, the reasoning behind using _ in js is that it is a short identifier. However, in java we have static imports. So, we can name the static class whatever we want, import it, and have all the functions in the global namespace. 


I was thinking something like Functional. So you can do: 

Functional.each(collection, item-> {}); 

or, you can do: 

import static Functional

each(collection, item->{});


What do you think?

**Comment by javadev** [comment]
Underscore is a good name for the class. I will prepare a pull request.

**Comment by javadev** [comment]
'_' was changed with '$' :+1:

**Comment by javadev** [comment]
$ was changed with U.

**Comment by javadev** [comment]
U was changed with Underscore.
