### ISSUE TITLE
Consider adding a license file

### ISSUE THREAD

**Issue by vickychijwani** [javadev/underscore-java#10]
Hi, would you mind adding a LICENSE file to the root of repository? That would make it much simpler for others to use (and potentially modify) this library without having to guess what the legal implications might be. You can check out this website to help you choose an appropriate license: http://tldrlegal.com/. Thanks!

**Comment by vickychijwani** [comment]
Oh, I noticed the MIT license is mentioned in the documentation, you can close this. But it's still good to add a license file in the root of the repository :)

**Comment by javadev** [comment]
Agree, added license file.
