### ISSUE TITLE
Is it possible to have the root node on resulting map from 'fromXml'?

### ISSUE THREAD

**Issue by rodrigorosa** [javadev/underscore-java#105]
Hi! 
My xml doesn't have a "root" node, it starts with an info node and I would like to have this stuff on the resulting map. I took a look at the code and it seems to me that it could be achieved by using `createMap(document) `instead of `createMap(document.getDocumentElement())` - but that will change the current behavior - or creating a new version of createMap with Document as a parameter or, maybe, turning createMap a public method. Does that make any sense? Is there another way to do this?
Thank you, sir.

```java         @Test
    public void fromXml2() {
        String string
            = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "\n"
            + "<lotes>\n"
            + "  <lote>\n"
            + "    <codigo_filial>0000</codigo_filial>\n"
            + "    <safra>20162017</safra>\n"
            + "    <especie>Soja</especie>\n"
            + "  </lote>\n"
            + "\n"
            + "  <lote>\n"
            + "    <codigo_filial>0000</codigo_filial>\n"
            + "    <safra>20162017</safra>\n"
            + "    <especie>Soja</especie>\n"
            + "  </lote>\n"
            + "</lotes> ";
        
        System.out.println(FromXml.fromXml(string).toString());

        String expected = "{lotes={lote=[{codigo_filial=0000, safra=20162017, especie=Soja}, {codigo_filial=0000, safra=20162017, especie=Soja}]}}";
        assertEquals(expected, FromXml.fromXml(string).toString());
    }`

**Comment by javadev** [comment]
Hi!

Good idea, I support it.

Will prepare a pull request.

**Comment by javadev** [comment]
New version with root node support was released today!
