### ISSUE TITLE
$.where  if Tuple<String, T> used private Field have Exception

### ISSUE THREAD

**Issue by xiyoufang** [javadev/underscore-java#14]
private static final class WherePredicate<E, T> implements Predicate<E> {
        .....
        @Override
        public Boolean apply(final E elem) {
            for (Tuple<String, T> prop : properties) {
                try {
                    if (!elem.getClass().getField(prop.fst()).get(elem)
                            .equals(prop.snd())) {
                        return false;
                    }
                } catch (Exception ex) {
                    ex.getMessage();
                }

The  elem.getClass().getField(prop.fst()) can't get private Field .

**Comment by javadev** [comment]
@xiyoufang I can add suppor for the getMethod() compare. Is it suitable solution for you?

**Comment by javadev** [comment]
Pull request with fix is ready.

**Comment by xiyoufang** [comment]
thanks
