### ISSUE TITLE
What's the difference between `com.github.underscore` and `com.github.underscore.lodash`?

### ISSUE THREAD

**Issue by tfga-ebi** [javadev/underscore-java#166]
When you add the import, the IDE asks you to chose between those two, and I couldn't find any mention anywhere saying what the difference might be.

**Comment by javadev** [comment]
Hi,

Thank you for using underscore library.

Lodash was separate library some month ago. It was merged to main library.

In general lodash is a good choice. You may use it.

Kind regards, Valentyn

**Comment by javadev** [comment]
Lodash U was moved to the underscore package. U class was renamed to the Underscore.
