### ISSUE TITLE
Can not resolve “$” underscore-java

### ISSUE THREAD

**Issue by pritanshupatel** [javadev/underscore-java#17]
I am new to underscore-java, facing issue running below code which says "$" can not resolve
$.each(asList(1, 2, 3), new Block<Integer>() {
    public void apply(Integer item) {
        System.out.println(item + ",");
    }
});

using java 1.7

**Comment by javadev** [comment]
You need to add import for the $ and Block classes.

import com.github.underscore.$;
import com.github.underscore.Block;

**Comment by pritanshupatel** [comment]
thanks  now its working fine :)
