### ISSUE TITLE
fromXml: XML secure processing causes exception on Android devices

### ISSUE THREAD

**Issue by timawesomeness** [javadev/underscore-java#215]
https://github.com/javadev/underscore-java/blob/master/src/main/java/com/github/underscore/lodash/Xml.java#L1353

```
javax.xml.parsers.ParserConfigurationException: http://javax.xml.XMLConstants/feature/secure-processing
at org.apache.harmony.xml.parsers.DocumentBuilderFactoryImpl.setFeature(DocumentBuilderFactoryImpl.java:101)
at com.github.underscore.lodash.Xml.createDocument(Xml.java:1353)
at com.github.underscore.lodash.Xml.fromXml(Xml.java:1283)
```

Secure XML processing is a desirable feature for many people, so it'd be best to either make it user-configurable or at the very least catch and ignore that exception to allow parsing where secure processing is unavailable.

**Comment by javadev** [comment]
Hi,

Thank you for reporting about exception in Android. I will prepare a fix.

**Comment by javadev** [comment]
New labrary version was released. 🎉
