### ISSUE TITLE
converting xml to json: self-closing tag

### ISSUE THREAD

**Issue by DubZyy** [javadev/underscore-java#221]
Hi,
I'm working with this nice lib to convert xml/json data and run into some problem with the "-self-closing" : "true" result, if the source xml node is like `<nodename />`.

to be honest: I didnt studied the code now and I'm not a java expert. But it seems, that there is no way to deactive the value "self-closing" with e.g. an argument?! Is such a feature planned?

May I ask you, why you add these self-closing feature? IMO I dont understand why to set an object with this value. I run into trouble with my frontend webapp with the resulting json I get with this lib. Dont you agree that something like `{ "nodename" : null }` is more the result to expect?
Also I dont think that the current integration is 100% json correct. your self-closing : "true" is set as string instead of boolean.
Would be great to hear about what you think, if there are any easy workarounds or sth similar. Thx in advance!
BR

**Comment by javadev** [comment]
Hi,

Thank you for the issue.

Which method do you use in your application `U.xmlToJson()` or `U.fromXml()` ?

I can add a conversion mode for these methods to replace "-self-closing" : "true" with null.

Sincerely

**Comment by DubZyy** [comment]
Hi,
first thanks a lot for your very fast response. I'm using xmlToJson method (about this issue). A conversion mode sounds nice. How will it work then? Will this be implemented in an official release?
Thank you!

PS: I also use jsonToXml. I did a quick check what happens with `{ "nodename" : null `} to xml which results in` <nodename null="true" />` which is ok I think.

BR

**Comment by javadev** [comment]
Hi,
> How will it work then? Will this be implemented in an official release?
It may be a new parameter for the `xmlToJson(String xml)` method.

I suggest to add a mode REPLACE_SELF_CLOSE_WITH_NULL.

Code example `String json = xmlToJson(xml, Mode.REPLACE_SELF_CLOSE_WITH_NULL);`

Will it be Ok?

Sincerely

**Comment by DubZyy** [comment]
Hi,
ok I understand. That sounds great! Thx a lot!
BR

**Comment by javadev** [comment]
It will be implemented with version 1.49.

**Comment by javadev** [comment]
New library was released. 🎉

**Comment by DubZyy** [comment]
May I ask you to upload the v1.49 binary file on http://javadev.github.io/underscore-java/ ?
Thanks in advance!

**Comment by javadev** [comment]
@DubZyy The link to binary jar file. https://repo1.maven.org/maven2/com/github/javadev/underscore/1.49/underscore-1.49.jar

**Comment by DubZyy** [comment]
Thx a lot. Checked new mode function. Works like a charm. Bye *thumbs up*
