### ISSUE TITLE
How can we remove XML root tags and some nested tags too ?

### ISSUE THREAD

**Issue by javaHelper** [javadev/underscore-java#229]
How can we remove XML root tags and some nested tags too ?

**Comment by javadev** [comment]
Hi @javaHelper.

You may read xml to a map, change it and then convert to xml back.

**Comment by javadev** [comment]
You my check method U.removeMinusesAndConvertNumbers(map) as example.

**Comment by javaHelper** [comment]
Could you please guide how to remove : "#omit-xml-declaration": "yes"? I dont see any comments in the code to understand API, its getting thought to understand it.

**Comment by javadev** [comment]
It may be a new method.

`Map<String, Object> result = U.<Map<String, Object>>remove(map, "#omit-xml-declaration");`

I will prepare a pull request.

**Comment by javaHelper** [comment]
Thanks ! It make sense.

**Comment by javadev** [comment]
The new version was released today. 🎉
