### ISSUE TITLE
Compatitable with Java 1.7?

### ISSUE THREAD

**Issue by johnnylc** [javadev/underscore-java#236]
It is stated that the library reqirements is "Java 1.6 and later, Java 1.8 or Java 11". 
When I use the library in my project built with Java 1.7, there are errors with some of the functions. 
So I want to know is this library compatitable with Java 1.7 ?
Could you please suggest a version of the library to be used with Java 1.7 ?
Thank you.

**Comment by javadev** [comment]
Yes, this library is compartible with Java 1.7.

**Comment by javadev** [comment]
Hi @johnnylc, 

Starting from version 1.61 minimum java is 1.8.

**Comment by javadev** [comment]
Starting from version 1.82 minimum java is 11.
