### ISSUE TITLE
toXml(collection) override root and element tag names

### ISSUE THREAD

**Issue by Cuneytt** [javadev/underscore-java#247]
toXml(collection) tag names are hardcoded to be "root" and "element"
Is there a way to override them?

Thanks

**Comment by javadev** [comment]
Hi,

Thank you for the issue.

I will try support for custom root and element strings.

**Comment by javadev** [comment]
I added a new method `U.rename(map, oldKey, newKey)`,

Code example:
```java
        Map<String, Object> map = U.newLinkedHashMap();
        map.put("-self-closing", "false");
        U.rename(map, "test", "test1");
        Map<String, Object> newMap = U.rename(map, "-self-closing", "-self-closing1");
        assertEquals("{\n"
            + "  \"-self-closing1\": \"false\"\n"
            + "}",
            U.toJson(newMap));
```
You may use it to rename `root` and `element` keys in map.
