### ISSUE TITLE
Keeps calling throttled functions after initial throttling works

### ISSUE THREAD

**Issue by johnsusek** [javadev/underscore-java#248]
Hello, I am using the throttling function like so:

```
  Supplier<Void> supplier = new Supplier<Void>() {
    public Void get() {
      LOGGER.info("Called expensive save operation!");
      return null;
    }
  };

  private Supplier<Void> throttledSave = U.throttle(supplier, 5000);
```

then, later in my application I call a few times in quick succession:

```
throttledSave.get();
```

In my console, the throttling appears to work (it takes 5 seconds for the first log message to appear).

But then I get the other operation logged as well a few seconds afterwards.

```
[15:30:49] [pool-7-thread-1/INFO] [ne.mv.se.ev.ServerModEventHandler/]: Called expensive save operation!
[15:30:52] [pool-8-thread-1/INFO] [ne.mv.se.ev.ServerModEventHandler/]: Called expensive save operation!
[15:30:52] [pool-9-thread-1/INFO] [ne.mv.se.ev.ServerModEventHandler/]: Called expensive save operation!
```

You can see at 15:30:49 that I get the first message, which is 5000ms after my call. This is good. But then 3 seconds later at 15:30:52 the throttled function gets called again twice. I would expect the throttled function only be called once, using the most recent call.

**Comment by javadev** [comment]
Hi John Susek,

Thank you for the issue.

I will check it locally and prepare a fix.

**Comment by javadev** [comment]
I prepared a fix https://github.com/javadev/underscore-java/pull/249

Have a nice day!

**Comment by javadev** [comment]
New version was released. 🎉
