### ISSUE TITLE
Handling Numbers and String Data Type

### ISSUE THREAD

**Issue by josephshirima** [javadev/underscore-java#268]
How can i convert Number presented on XML to be JSON Integer and Not String?

Example : &lt;a&gt;&lt;b&gt;100&lt;/b&gt;&lt;a&gt;  to be { "a" :  { "b" : 100 } } and NOT { "a" :  { "b" :  "100" } }

**Comment by javadev** [comment]
```xml
<a><b  number="true">100</b></a>
```
will be converted to json:
```json
{
  "a": {
    "b": 100
  },
  "#omit-xml-declaration": "yes"
}
```

**Comment by josephshirima** [comment]
Thank you!

**Comment by josephshirima** [comment]
How to convert XML to MAP? i need to remove a XML root element.

**Comment by javadev** [comment]
U.fromXmlMap(xmlstring) will convert xml to map.

**Comment by josephshirima** [comment]
Try to use it on spring boot app. But am getting this exception. What is may be a possible causes?

java.lang.ExceptionInInitializerError: null
	at com.github.underscore.lodash.U.fromXmlMap(U.java:2142) ~[underscore-1.58.jar:na]
	at com.github.underscore.lodash.U.fromXmlMap(U.java:2137) ~[underscore-1.58.jar:na]

**Comment by javadev** [comment]
I will preape s fix for it.

**Comment by javadev** [comment]
I prepared a fix: https://github.com/javadev/underscore-java/pull/269
