### ISSUE TITLE
JSON to XML conversion 

### ISSUE THREAD

**Issue by sreekanthpld** [javadev/underscore-java#278]
I have a json { "a":"value"}. I need to convert to xml like <root a="value" />

**Comment by javadev** [comment]
Hi,

Thank you for the question.

You may call U.jsonToXml(json).

Resulted xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<a>value</a>
```

**Comment by sreekanthpld** [comment]
Hi - Can I make it in tag rather than element. like this  `**<root a="value" />**`

**Comment by javadev** [comment]
You may try this json

```json
{ "-a":"value"}
```
