### ISSUE TITLE
How to replace null value with empty when use U.jsonToXml()

### ISSUE THREAD

**Issue by dejavuhuh** [javadev/underscore-java#285]
When I convert xml to json, I can use `U.xmlToJson(xml, U.Mode.REPLACE_EMPTY_VALUE_WITH_NULL)`
but when I convert json to xml, there is no way to replace null value with empty like `U.jsonToXml(json, U.Mode.REPLACE_NULL_VALUE_WITH_EMPTY)`
This brings some problems, for example, there is a xml content like below
```xml
<aaa>
    <bbb></bbb>
</aaa>
```
when I convert it to json
```java
String xml = "<aaa><bbb></bbb></aaa>"
String json = U.xmlToJson(xml, U.Mode.REPLACE_EMPTY_VALUE_WITH_NULL);
```
the json result is
```json
{
    "aaa": {
        "bbb": ""
    }
}
```
but, when I convert the json result to xml
```java
String xml = U.jsonToXml(json);
```
the xml result is
```xml
<aaa>
    <bbb null="true"/>
</aaa>
```
But this is not what i want

**Comment by javadev** [comment]
Thank you for the issue. I added a new mode REPLACE_NULL_VALUE_WITH_EMPTY to the U.jsonToXml() method.

**Comment by dejavuhuh** [comment]
thanks very much!

**Comment by javadev** [comment]
The new version library was released today. 🎉
