### ISSUE TITLE
How to convert xml to json with multiple U.Mode?

### ISSUE THREAD

**Issue by dejavuhuh** [javadev/underscore-java#293]
Such as
```java
String json = U.xmlToJson(xml, U.Mode.REPLACE_SELF_CLOSING_WITH_NULL, U.Mode.REPLACE_EMPTY_VALUE_WITH_NULL);
```
which can replace self closing with null and also replace empty value with null

Reversely, when convert json to xml
```java
String xml = U.jsonToXml(json, U.Mode.REPLACE_NULL_WITH_EMPTY_VALUE, U.Mode.REPLACE_EMPTY_VALUE_WITH_SELF_CLOSING);
```

At the same time, I hope to add some new Mode like:
```java
// replace <aaa></aaa> to "aaa": ""
U.xmlToJson(xml, U.Mode.REPLACE_EMPTY_TAG_WITH_EMPTY_VALUE);
```
and reversely
```java
// replace "a": "" to <aaa></aaa>
U.jsonToXml(json, U.Mode.REPLACE_EMPTY_VALUE_WITH_EMPTY_TAG);
```

**Comment by javadev** [comment]
Hello @dejavuhuh,

Thank you for improvement suggestion.

**Comment by dejavuhuh** [comment]
> Hello @dejavuhuh,
> 
> Thank you for improvement suggestion.

Hello @javadev,
Thank you for replying to me, and I suddenly remembered some situations like:
```java
// replace <aaa></aaa> to "aaa": null
U.xmlToJson(xml, U.Mode.REPLACE_EMPTY_TAG_WITH_NULL);
// and so on...
```
Last of the last, there will be 8 situations:
```java
// replace <aaa></aaa> to "aaa": null
// replace <aaa></aaa> to "aaa": ""
// replace <aaa /> to "aaa": null
// replace <aaa /> to "aaa": ""
```
and reversely
```java
// replace "aaa": null to <aaa></aaa>
// replace "aaa": "" to <aaa></aaa>
// replace "aaa": null to <aaa />
// replace "aaa": "" to <aaa />
```

**Comment by javadev** [comment]
I added two new modes for the U.xmlToJson(xml): REPLACE_EMPTY_TAG_WITH_NULL and REPLACE_EMPTY_TAG_WITH_EMPTY_STRING.

For U.jsonToXml(json) we have a mode: REPLACE_NULL_WITH_EMPTY_VALUE

**Comment by dejavuhuh** [comment]
> I added two new modes for the `U.xmlToJson(xml)`: `REPLACE_EMPTY_TAG_WITH_NULL and REPLACE_EMPTY_TAG_WITH_EMPTY_STRING`.
> 
> For `U.jsonToXml(json)` we have a mode: `REPLACE_NULL_WITH_EMPTY_VALUE`



> I added two new modes for the `U.xmlToJson(xml)`: `REPLACE_EMPTY_TAG_WITH_NULL and REPLACE_EMPTY_TAG_WITH_EMPTY_STRING`.
> 
> For `U.jsonToXml(json)` we have a mode: `REPLACE_NULL_WITH_EMPTY_VALUE`



> I added two new modes for the `U.xmlToJson(xml)`: `REPLACE_EMPTY_TAG_WITH_NULL and REPLACE_EMPTY_TAG_WITH_EMPTY_STRING`.
> 
> For `U.jsonToXml(json)` we have a mode: `REPLACE_NULL_WITH_EMPTY_VALUE`

Thanks, but I would like a mode for replacing `{ "aaa": "" }` to `<aaa></aaa>` instead of `<aaa string="true"/>`
like
```java
String xml = U.jsonToXml("{ \"aaa\": \"\" }", U.Mode.REPLACE_EMPTY_STRING_WITH_EMPTY_TAG);
System.out.println(xml); // <aaa></aaa>
```

**Comment by dejavuhuh** [comment]
> I added two new modes for the `U.xmlToJson(xml)`: `REPLACE_EMPTY_TAG_WITH_NULL and REPLACE_EMPTY_TAG_WITH_EMPTY_STRING`.
> 
> For `U.jsonToXml(json)` we have a mode: `REPLACE_NULL_WITH_EMPTY_VALUE`

Thanks, but I would like a mode for replacing `{ "aaa": "" }` to `<aaa></aaa>` instead of `<aaa string="true"/>`
like
```java
String xml = U.jsonToXml("{ \"aaa\": \"\" }", U.Mode.REPLACE_EMPTY_STRING_WITH_EMPTY_TAG);
System.out.println(xml); // <aaa></aaa>
```

**Comment by javadev** [comment]
@dejavuhuh I added new mode `REPLACE_EMPTY_STRING_WITH_EMPTY_VALUE` to the `U.jsonToXml(json)` method.

**Comment by dejavuhuh** [comment]
> @dejavuhuh I added new mode `REPLACE_EMPTY_STRING_WITH_EMPTY_VALUE` to the `U.jsonToXml(json)` method.

Thanks very much!

**Comment by javadev** [comment]
The new version was released today. 🎉

**Comment by dejavuhuh** [comment]
> Hello @dejavuhuh,
> 
> Thank you for improvement suggestion.

@javadev Hey, I am glad to see that you just released a new version a week ago, but it seems that multiple U.Mode still not supported?

**Comment by javadev** [comment]
Hello @dejavuhuh,

I added two new modes for xmlToJson method.

What other modes do you need?

**Comment by dejavuhuh** [comment]
> Hello @dejavuhuh,
> 
> I added two new modes for xmlToJson method.
> 
> What other modes do you need?

Like this, which can replace self closing with null and also replace empty value with null
```java
String json = U.xmlToJson(xml, U.Mode.REPLACE_SELF_CLOSING_WITH_NULL, U.Mode.REPLACE_EMPTY_VALUE_WITH_NULL);
```
I can pass two or more U.Mode into the xmlToJson (or jsonToXml) method

**Comment by javadev** [comment]
Hi @dejavuhuh,

The new mode `REPLACE_EMPTY_TAG_WITH_NULL`
replaces emply tag and self closing tag with null.
