### ISSUE TITLE
How to replace root element  in generated XML with custom root name?

### ISSUE THREAD

**Issue by Sriram1404** [javadev/underscore-java#295]
Please let me know how to replace the <root> element with custom name for generated xml output?

Please provide the sample example for better understanding.

**Comment by javadev** [comment]
Hi @Sriram1404,

Thank you for your question.

The example how to generate xml from json with a custom root name.

```java
        assertEquals("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<json>\n"
                        + "  <a>b</a>\n"
                        + "  <c>d</c>\n"
                        + "</json>",
                U.jsonToXml("{\"a\": \"b\", \"c\": \"d\"}", "json"));
```

**Comment by Sriram1404** [comment]
Thanks for your quick response.
