### ISSUE TITLE
How to create the xml with attributes using underscore-java lib?

### ISSUE THREAD

**Issue by Sriram1404** [javadev/underscore-java#296]
Please let me know how to create the xml with attributes and its corresponding values using Underscore-java lib?

I want to achieve the following using underscore-java lib,

<user id="1">
<name>AAA</name>
<dept>CSE</dept>
</user>

<user> tag followed by its attributes and its corresponding are possible to create via underscore-java lib. Also please provide the sample example for better understanding.

**Comment by javadev** [comment]
Hi @Sriram1404,

Thank you for the question.

The example is:

```java
U.jsonToXml("{\"a\":{\"-attr\":\"c\",\"b\":\"data\"}}");
    // <?xml version="1.0" encoding="UTF-8"?>
    // <a attr="c">
    //   <b>data</b>
    // </a>
```

**Comment by Sriram1404** [comment]
Thanks a lot  for clear cut example.

**Comment by javadev** [comment]
We can use any character in json key:

```json
{"a":{"-!@#$%^&":"c","b":"data"}}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<a __EE____IA____EM____EQ____EU____LY____EY__="c">
  <b>data</b>
</a>
```
