### ISSUE TITLE
What is the purpose of FromType paramater in U.fromXmlToMap() method?

### ISSUE THREAD

**Issue by Sriram1404** [javadev/underscore-java#297]
Please let me know what is the exact purpose of FromType paramater in U.fromXmlToMap() method? please provide the sample example for better understanding.

Also please let me know is it possible to extract the nested tags elements from the given root element while converting xml to map conversion and also provide the API for the same and provide the sample example for better understanding.

BR
Sriram Muralidharan

**Comment by javadev** [comment]
Hello @Sriram1404 

This is a unit test for this method.

```java
    public void fromXmlMap() {
        String stringXml =
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
        + "\n<root empty-array=\"true\"></root>";
        assertEquals("{value=[]}", U.fromXmlMap(stringXml).toString());
        String stringXml2 =
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
        + "\n<root></root>";
        assertEquals("{}", U.fromXmlMap(stringXml2).toString());
        String stringXml3 =
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
        + "\n<root></root>";
        assertEquals("{}", U.fromXmlMap(stringXml3, Xml.FromType.FOR_CONVERT).toString());
    }
```

**Comment by Sriram1404** [comment]
Please let me know is it possible to extract the nested tags elements from the given root element while converting xml to map conversion and also provide the API for the same and provide the sample example for better understanding.
