### ISSUE TITLE
How to get the deeply nested xml elements while converting from xml to map? 

### ISSUE THREAD

**Issue by Sriram1404** [javadev/underscore-java#299]
Please let me know is it possible to extract the nested tags elements from the given root element while converting xml to map conversion not all the xml elements only from the particular root element and also provide the API for the same and provide the sample example for better understanding.

**Comment by Sriram1404** [comment]
hope my query is clear.

**Comment by Sriram1404** [comment]
Instead of converting the all xml to map if i gave the root element from that root element all of its child elements only should be stored on map. Eample Level1->Level2->child1
                                                             ->child2

so if i given the required level in API for example  level1.level2  then only all the child elements of Level2 only stored in map rest all other xml elements are ignored.

**Comment by javadev** [comment]
Hello @Sriram1404,

Thank you for your question.

There is a U.get(map, path) method available.

```java
/*
_.get({"a":[{"b":{"c":"d"}}]}, "a[0].b.c");
// → "d"
*/
    @SuppressWarnings("unchecked")
    @Test
    public void get() {
        assertEquals("d", U.<String>get(
                (Map<String, Object>) U.fromJson("{\"a\":[{\"b\":{\"c\":\"d\"}}]}"), "a[0].b.c"));
    }
```

**Comment by Sriram1404** [comment]
Thanks for your prompt reply.
