### ISSUE TITLE
Improvising on performance.

### ISSUE THREAD

**Issue by jamalahmedmaaz** [javadev/underscore-java#3]
Hi Valentyn,

I will like to help you in improvising on memory usage. I am using the current version. Will recommend to use Guava for collections. As we are using it a lot.

If you approve i will do the changes and push.

**Comment by javadev** [comment]
Hi,

It will be nice to optimaze memory usage for the library.

**Comment by jamalahmedmaaz** [comment]
Hi,

You have closed the issue sir. I can push the code. with your approval. Doesnt want to duplicate code. Are you doing any optimization or else i can push.

**Comment by javadev** [comment]
It will be nice to check yor changes with pull request.

**Comment by javadev** [comment]
Support for guava collection was added. :+1:
