### ISSUE TITLE
Remove string="true" attribute while converting json to xml

### ISSUE THREAD

**Issue by Sriram1404** [javadev/underscore-java#301]
please let me know how to remove the string="true" while converting json to xml using underscore lib.
please provide the sample example for better understanding.

**Comment by javadev** [comment]
Hi @Sriram1404,

Thank you for your question.

I added new mode `REPLACE_EMPTY_STRING_WITH_EMPTY_VALUE` to the `U.jsonToXml(json)` method.

It will be available in version 1.67.

**Comment by javadev** [comment]
The new version was released today. 🎉

**Comment by Sriram1404** [comment]
Thanks for letting me know
