### ISSUE TITLE
Convert xml to json

### ISSUE THREAD

**Issue by Sriram1404** [javadev/underscore-java#305]
I am getting the API response as following XML,
`<a>
    <b ID="0">
        <c>10020</c>
        <d>NEWYORK</d>
        <e>NY</e>
    </b>
    <b ID="1">
        <c>06373</c>
        <d>OLDLYME</d>
        <e>CT</e>
    </b>
</a>`

I want to convert the above xml to json as follows,

`{
    "b": [
        {
            "c": "10020",
            "d": "NEWYORK",
            "e": "NY"
        },
        {
            "c": "06373",
            "d": "OLDLYME",
            "e": "CT"
        }
    ]
}`

I have already tried U.xmlToJson(), U.fromXmlWithoutAttributes() but unable to achieve the above expected result.(Skip the root element `<a>`  and also skip xml element attributes("ID") ). Please let me know will this achieved by using Underscore-lib?

**Comment by javadev** [comment]
You may made back conversion json to xml.

The service here https://javadev.github.io/xml-to-json/

**Comment by Sriram1404** [comment]
Hi Sir, Thanks for prompt response. I won't convert back json to xml. I will convert the xml response to json and send it back to client.  please let me know is there any way to achieve the expected json result (mentioned in my previous comment) by skipping the XML root element and also the attribute values?

**Comment by javadev** [comment]
To get json

```json
{
   "b": [
      {
         "c": "10020",
         "d": "NEWYORK",
         "e": "NY"
      },
      {
         "c": "06373",
         "d": "OLDLYME",
         "e": "CT"
      }
   ]
}
```

you need this XML
```xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <b>
    <c>10020</c>
    <d>NEWYORK</d>
    <e>NY</e>
  </b>
  <b>
    <c>06373</c>
    <d>OLDLYME</d>
    <e>CT</e>
  </b>
</root>
```

**Comment by javadev** [comment]
This XML

```xml
<a>
   <b ID="0">
      <c>10020</c>
      <d>NEWYORK</d>
      <e>NY</e>
   </b>
   <b ID="1">
      <c>06373</c>
      <d>OLDLYME</d>
      <e>CT</e>
   </b>
</a>
```

will be converted to this json
```json
{
  "a": {
    "b": [
      {
        "-ID": "0",
        "c": "10020",
        "d": "NEWYORK",
        "e": "NY"
      },
      {
        "-ID": "1",
        "c": "06373",
        "d": "OLDLYME",
        "e": "CT"
      }
    ]
  },
  "#omit-xml-declaration": "yes"
}
```

**Comment by Sriram1404** [comment]
Thanks sir for spending yours valuable time and let me check whether i could use the xml to json conversion as it is.

**Comment by javadev** [comment]
I may add a new mode to the xmlToJson method REMOVE_FIRST_LEVEL. Will it be good for you?

**Comment by Sriram1404** [comment]
Yes sir, it will be really helpful for me. Sir, also please let me know how long this change will took time to complete ?

**Comment by javadev** [comment]
Implemented https://github.com/javadev/underscore-java/pull/307

**Comment by javadev** [comment]
The new version was released today. 🎉
