### ISSUE TITLE
Build json with null value

### ISSUE THREAD

**Issue by petersramek** [javadev/underscore-java#306]
Hello!

Not sure if this is an issue or I'm not aware how it works, but I'm trying to build a json which contains null values e.g:

```json
{
    "firstName": "John",
    "lastName": null
}
```

```java
U.Builder builder = U.objectBuilder()
    .add("firstName", "John")
    .add("lastName", null) //How to insert null value here 
```

Any advice how to achieve this?

Thank in advance!

**Comment by javadev** [comment]
Hi @petersramek,

Thank you for the issue.

I added support for null in object builder.

```
        String json = U.objectBuilder()
            .add("firstName", "John")
            .add("lastName", (U.Builder) null)
            .toJson();
```

It will be available in the nearest release.

**Comment by petersramek** [comment]
Hi @javadev,

Thank you!

**Comment by javadev** [comment]
The new method `addNull(key)` will be added.

**Comment by javadev** [comment]
The new method was added U.objectBuilder().addNull("key").
