### ISSUE TITLE
Retaining the mandatory <root> during jsontoxml conversion

### ISSUE THREAD

**Issue by nayakmk** [javadev/underscore-java#311]
Hi, 

Is this possible to always retain the `root` irrespective of how the JSON is, in the final XML?

Regards,
Malaya

**Comment by javadev** [comment]
Hi @nayakmk,

Thank you for the issue.

Please add example for converting with actual result and expected result.

**Comment by nayakmk** [comment]
Thanks for the response @javadev, I have added some samples below. 

1. Input JSON

```
{
  "data": [
    {
      "a": "b"
    }
  ]
}
```
Current Output: 
```
<?xml version="1.0" encoding="UTF-8"?>
<data array="true">
  <a>b</a>
</data>
```

Expected output: 

```
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <data array="true">
    <a>b</a>
  </data>
</root>
```

2. The ability to pass multiple modes before the final XML is derived. 

e.g. U.jsonToXml(jsonData).mode(U.Mode.MODE1).mode(U.Mode.MODE2).build();

**Comment by javadev** [comment]
Thank you for example. I can add a new mode to the jsonToXml FORCE_ROOT_JSON_TO_XML.

For the second question. Please add example with multiple mode and expected result of converting.

**Comment by nayakmk** [comment]
For the multiple modes, we can take the same example but also want to change the root name. 

Order: 
1. FORCE_ROOT_JSON_TO_XML
2. DEFINE_ROOT_NAME

```
{
  "data": [
    {
      "a": "b"
    }
  ]
}
```

```
<?xml version="1.0" encoding="UTF-8"?>
<newroot>
  <data array="true">
    <a>b</a>
  </data>
</newroot>
```

**Comment by javadev** [comment]
For this case, I will add a newRootName support.

```java
        assertEquals(
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                        + "<newroot>\n"
                        + "  <data array=\"true\">\n"
                        + "    <a>b</a>\n"
                        + "  </data>\n"
                        + "</newroot>",
                U.jsonToXml(
                        "{\n"
                                + "  \"data\": [\n"
                                + "    {\n"
                                + "      \"a\": \"b\"\n"
                                + "    }\n"
                                + "  ]\n"
                                + "}",
                        U.Mode.FORCE_ADD_ROOT_JSON_TO_XML, "newroot"));
```

**Comment by javadev** [comment]
Implementation was added and will be released soon.

**Comment by javadev** [comment]
The new version was released today 🎉
