### ISSUE TITLE
Is there a get for nested hetrogenus maps? 

### ISSUE THREAD

**Issue by favetelinguis** [javadev/underscore-java#313]
In change list i can find "Added support for the get(object, path) method in lodash". However im no able to find a get in the Api? Is there a get that works over nested maps with lists?

**Comment by javadev** [comment]
Hi @favetelinguis,

Thank you for the issue.

I will copy example from a unit test.

**Comment by favetelinguis** [comment]
Thanks, can underscore-java be used with immutable collections also?

**Comment by javadev** [comment]
Method get accepts a Map interface.
