### ISSUE TITLE
xml nil="true" support

### ISSUE THREAD

**Issue by tttomat19** [javadev/underscore-java#316]
Thanks for the lib. Especially the xml part.

There seems to be lack of `<b:mytag i:nil="true"/>` (`nil="true"`) support.

Is there any workaround or advice on how to implement it in `Xml.java` file ?

**Comment by javadev** [comment]
I added the new method support U.replaceNilWithNull(map).

https://github.com/javadev/underscore-java/pull/318

**Comment by javadev** [comment]
The new version was released today 🎉
