### ISSUE TITLE
How to make json string to beautiful json format with color 

### ISSUE THREAD

**Issue by hafiz013** [javadev/underscore-java#362]
Hi how to make string json to beautiful json format with different color (header difference color) (value difference color)?

**Comment by javadev** [comment]
Hi @hafiz013,

Thank you for your question.

Do you mean generate html for json?

**Comment by hafiz013** [comment]
@javadev. From ResponseBody (okhttp3) to beautiful json format like this  with color
<img width="699" alt="MicrosoftTeams-image (3)" src="https://user-images.githubusercontent.com/6707224/171148444-be39a177-9ed8-4dff-b7aa-f28862e82b9b.png">
)

**Comment by hafiz013** [comment]
@javadev  is there any library can do change color from this json strings?

**Comment by javadev** [comment]
I think it is a setting for library that visualize json.

**Comment by hafiz013** [comment]
how to visualize json @javadev
