### ISSUE TITLE
Is the source for xmltojson.jar available?

### ISSUE THREAD

**Issue by geert56** [javadev/underscore-java#363]
Under releases/test I find the nice toolkit xmltojson.jar. The sources (.zip and tar.gz) listed there are
from 2018 and don't seem to correspond to what's in the jar file. Are the Java sources for the jar
available somewhere? Thanks!

**Comment by javadev** [comment]
Hi @geert56,

Thank you for the question.

Xmltojson.jar is a desktop/command line application.

It is available here

https://github.com/javadev/underscore-java/releases/tag/test

It uses library as dependency. The source codes are closed for now.

**Comment by javadev** [comment]
The console application has been updated.

**Comment by geert56** [comment]
Thanks for the newer version of the xmltojson CLI tool. Please mention that it presumably requires java 11.

**Comment by javadev** [comment]
The console application has been upgraded to version 2025-02-22.
