### ISSUE TITLE
once() behavior

### ISSUE THREAD

**Issue by liorshalev01** [javadev/underscore-java#37]
Shouldn't once() behavior should be as with underscore.js, and return the return value of the inner function? For now it looks like it ignores the inner function result, and just return null.

**Comment by javadev** [comment]
I prepared a fix, https://github.com/javadev/underscore-java/pull/38

**Comment by liorshalev01** [comment]
Thank you,
I think the same case is also with $.before()

**Comment by javadev** [comment]
I prepared a fix for after() and before() methods, https://github.com/javadev/underscore-java/pull/39
