### ISSUE TITLE
Adding SUM, MEAN, MEDIAN, NRANGE.

### ISSUE THREAD

**Issue by jamalahmedmaaz** [javadev/underscore-java#4]
Hi,

Will like to add these function, can you please approve.

**Comment by javadev** [comment]
This is are arithmetical functions. How they will work with strings and objects?

**Comment by jamalahmedmaaz** [comment]
This functions are possible for Number Objects and Date objects. With your approval push some code.

**Comment by javadev** [comment]
Good. Please create a pull request. I will check.

**Comment by javadev** [comment]
$.sum(array) implementation was added in branch #4.
