### ISSUE TITLE
Template with JSON parameter

### ISSUE THREAD

**Issue by PayasKrishna** [javadev/underscore-java#45]
Hi,

Thanks for the awesome library. I had been looking for underscore.js functionality in java when I found this! However, I have been trying to use underscore-java to get a functionality similar to following:

.template(_.each(items, function(item) { `<Tag>` ${item.name} `<\Tag>` }), 
where items is a JSON, for example: "{name: 'ABC', name: 'PQR'}"

The output should be "`<Tag>` ABC `</Tag>` `<Tag>`  PQR `</Tag>`"

Is it possible to achieve this?

Regards
Payas

**Comment by javadev** [comment]
Hi, Payas.

Thank you for your question. I will try to prepare a unit test and pull request with support json for the `template` method.

Best regards
Valentyn

**Comment by javadev** [comment]
```java
        $.templateSettings(new HashMap<String, String>() { { put("interpolate", "\\$\\{([\\s\\S]+?)\\}");
            put("evaluate", "\\{\\{([\\s\\S]+?)\\}\\}"); } });
        String list = "{{ _.each(items, function(item) { }} <li>${ item }</li> {{ }); }}";
        Template<Set<Map.Entry<String, Object>>> compiled3 = $.template(list);
        assertEquals(" <li>moe</li>  <li>curly</li>  <li>larry</li> ",
            compiled3.apply((new LinkedHashMap<String, Object>() { {
                put("items", asList("moe", "curly", "larry")); } }).entrySet()));
```

I prepared an example with ${} wrapper for the variable in template.

**Comment by PayasKrishna** [comment]
Hi Valentyn, 

Thanks for the quick response! The test case for ${ .. } works. 

However, I was wondering if something like ${item.<i>property</i>} works as well. We note that ${item} works, where item is a String. What if `item` is a more complex object, with some `item.property` as well?

In one case, `items` can be a JSON: {property: "something", property: "somethingElse"}. Can we use `Template` class now? This idea can be arbitrarily expanded: with any level of nesting via a JSON string. 

I tried to look into the source code but couldn't conclude. Can you please help?

Best,
Payas

**Comment by javadev** [comment]
Hi Payas,

What if item is a more complex object, with some item.property as well?

No, it will not work. Template replacer checks for the variable name inside function() and changes it inside function's body.

As I know JSON is not allowed to use the key duplicates.

Best regards, Valentyn

**Comment by PayasKrishna** [comment]
Hi Valentyn,

I guessed as much, but thanks for confirming. And another thanks for such quick replies. :)

Best,
Payas
