### ISSUE TITLE
Could you please atleast a simple document to use the underscore template API.

### ISSUE THREAD

**Issue by FirstSamurai** [javadev/underscore-java#47]
Like basic usage of the template in java. Eg: 

        <h2>
            <%- listTitle %>
        </h2>
        <ul>
            <% _.each( listItems, function( listItem ){ %>
                <li>
                    <%- listItem.name %>
                    <% if ( listItem.hasOlympicGold ){ %>
                        <em>*</em>
                    <% } %>
                </li>
            <% }); %>
        </ul>

        <% var showFootnote = _.any(
            _.pluck( listItems, "hasOlympicGold" )
        ); %>

        <% if ( showFootnote ){ %>
            <p style="font-size: 12px ;">
                <em>* Olympic gold medalist</em>
            </p>
        <% } %>

If the above template can be manipulated using the api, thank you so much.

**Comment by javadev** [comment]
It is not supported for now. You may try to use mustache.js java port.
http://www.javarants.com/2010/05/03/the-ideal-web-application-templating-system/

**Comment by FirstSamurai** [comment]
Any plans of supporting it in the future?

**Comment by javadev** [comment]
It will be nice to add support templates like in mystache.java.
