### ISSUE TITLE
Add Base32 RFC 4648 alphabet 

### ISSUE THREAD

**Issue by axelfontaine** [javadev/underscore-java#554]
Base32 support currently uses a non-standard alphabet. It would be nice if this could either be made customizable or if RFC 4648 could be supported.

See https://en.wikipedia.org/wiki/Base32

**Comment by javadev** [comment]
@axelfontaine

Custom Base32 encoding is employed for XML tag names where numbers are not permitted. The class is open for use, and third-party applications are welcome to reuse it.

**Comment by javadev** [comment]
Thank you for bringing this to my attention. I will investigate how to incorporate support for the new Base32 encoding.

**Comment by javadev** [comment]
Several code changes are required for the custom Base32. It might involve a forked repository with a modified class

https://github.com/javadev/underscore-java/pull/558/files
