### ISSUE TITLE
How could i use it in Java 8 project?

### ISSUE THREAD

**Issue by JohnnieWind** [javadev/underscore-java#572]
my project is Java 8,  i want to use in my project.
but, can't run my project, so sad.

**Comment by javadev** [comment]
The build for Java 8 was generated for version 1.81.

https://github.com/javadev/underscore-java/releases/tag/v1.81

**Comment by JohnnieWind** [comment]
> The build for Java 8 was generated for version 1.81.
> 
> https://github.com/javadev/underscore-java/releases/tag/v1.81

THX
^ ^
