### ISSUE TITLE
Question: XML to JSON attribute prefix

### ISSUE THREAD

**Issue by robertovanderlinden** [javadev/underscore-java#577]
Hello,

When we convert an XML to JSON the attributes are prefixed with "-". 
Are we able to change this to "@"?

XML:
`<Reference Type="Organisation ID" AssignedBy="Buyer">someValue</Reference>`

Current JSON output:
```
"Reference": {
               "-Type": "Organisation ID",
               "-AssignedBy": "Buyer",
                "#text": "someValue"
              },
```

**Comment by javadev** [comment]
I've introduced a new XML to JSON conversion mode: `U.XmlToJsonMode.REPLACE_MINUS_WITH_AT`.

https://github.com/javadev/underscore-java/pull/578

```java
        assertEquals(
                "{\n"
                        + "  \"a\": {\n"
                        + "    \"@c\": \"1\"\n"
                        + "  },\n"
                        + "  \"#omit-xml-declaration\": \"yes\"\n"
                        + "}",
                U.xmlToJson(
                        "<a c=\"1\"></a>", U.XmlToJsonMode.REPLACE_MINUS_WITH_AT));
```

**Comment by javadev** [comment]
I add new mode XmlToJsonMode.REPLACE_EMPTY_TAG_WITH_NULL_AND_MINUS_WITH_AT

https://github.com/javadev/underscore-java/pull/579
