### ISSUE TITLE
Ignore colon (:) in root element if specified.

### ISSUE THREAD

**Issue by amdhanwate** [javadev/underscore-java#604]
I have a json, say:

```json
{
    "ns2:tag": "value"
}
```

When I convert the above json using `U.jsonToXml(jsonString, Xml.XmlStringBuilder.Step.TWO_SPACES);`, I get the below output:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ns2__HI__tag>value</ns2__HI__tag>
```

Expected output:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ns2:tag>value</ns2:tag)>
```

I know this might be because of some specific naming convention or transformation but I couldn't proceed without the tag being in same format as expected output. If the community could suggest an workaround on the issue that would be really helpful.

**Comment by javadev** [comment]
Hi @amdhanwate 

Thank you for bringing up this matter.

You can include a namespace in the JSON to receive a prefix with ":" in XML.
