### ISSUE TITLE
Unable to import 1.107 version

### ISSUE THREAD

**Issue by sxp267** [javadev/underscore-java#689]
Getting this error

![image](https://github.com/user-attachments/assets/2b671321-5553-48c0-b6a2-49c0ef70934d)

I had 1.58 which I'm trying to migrate to 1.107 but not sure why getting above error and all the references are getting broken. Any issues from my side or  this one is not a stable version ?

**Comment by javadev** [comment]
It seems to be an IDE issue. The library is available, and Java 11 is required.

https://central.sonatype.com/artifact/com.github.javadev/underscore/1.107
