### ISSUE TITLE
XML to Json parsing error questions

### ISSUE THREAD

**Issue by superuser1444** [javadev/underscore-java#692]
Hi, thank you for creating such a great library.
I'm using that library to convert XML to JSON.
It's working fine, but I've noticed some issues while using it.
For example, if you convert the following ServicePolicy.xml (https://gist.github.com/istolga/bce09bec9ed293e2bcb9f9c7e4bfbbe2) to json, the problem is as follows.

------------------------------------------------------------------------------------------

#XML
<L7p:Comment stringValue="============================"/>

#JSON
"L7p:Comment": {
    "-stringValue": "",
    "-self-closing": "true"
}

------------------------------------------------------------------------------------------

Is there a workaround for the above issue?

**Comment by javadev** [comment]
Hello @superuser1444 

Thank you for the issue. I will investigate it.

**Comment by javadev** [comment]
I have prepared a fix https://github.com/javadev/underscore-java/pull/693

**Comment by javadev** [comment]
The issue will be addressed in version 1.109

**Comment by javadev** [comment]
As a workaround, you might consider using version v1.91

**Comment by javadev** [comment]
The new library version with a fix was released!
