### ISSUE TITLE
JLS discourages use of _ as a variable name in any context

### ISSUE THREAD

**Issue by vickychijwani** [javadev/underscore-java#7]
From [JLS §15.27.1. Lambda Parameters](http://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.27.1):

> The use of the variable name _ in any context is discouraged. Future versions of the Java programming language may reserve this name as a keyword and/or give it special semantics.

Since the JLS is explicit about it, you should consider changing the variable name to something else, maybe `$`?

**Comment by vickychijwani** [comment]
For what it's worth, this little naming issue is stopping me from using the library.

**Comment by javadev** [comment]
Hi,

I prepared a pull request to rename _ with $. :)

**Comment by vickychijwani** [comment]
I'm sorry, I hadn't done my research on whether `$` is a safe name to use. From [JLS §3.8. Identifiers](http://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-JavaLetter):

> The "Java letters" include uppercase and lowercase ASCII Latin letters A-Z (\u0041-\u005a), and a-z (\u0061-\u007a), and, for historical reasons, the ASCII underscore (_, or \u005f) and dollar sign ($, or \u0024). The $ sign should be used only in mechanically generated source code or, rarely, to access pre-existing names on legacy systems.

Really sorry to suggest another troublesome name. Do you think there's another name you could use?

**Comment by javadev** [comment]
If both names _ and $ aren't recomended we can leave existing name _, :-)

**Comment by vickychijwani** [comment]
In that case I think `$` is the lesser of the 2 evils. `$` can still be used for "legacy systems", but `_` might become a reserved keyword soon, which is much worse. What do you think? :)

**Comment by vickychijwani** [comment]
I'm wondering, is there a way to let users of the library configure what name to use? I'm not a Java expert so I don't know how to do it, but maybe you do.

**Comment by javadev** [comment]
OK. $ is more safe than _. Let's use $. In java we can use classifier attribute for versions of the modules.

https://maven.apache.org/pom.html

It may be one more version with underscore if needed,

**Comment by javadev** [comment]
Implemented with pull requests #8 and #9.

**Comment by vickychijwani** [comment]
Great, thanks for resolving this! How do I use the classifier attribute?

Also, thanks for creating this project, the open-source community appreciates it! :)

**Comment by javadev** [comment]
Classifier attribute is not support for now, but may be added later to support library with _ sign.

**Comment by javadev** [comment]
$ was renamed to Underscore and U.
