### ISSUE TITLE
Poor Performance intersection method, and include new notIntersection method

### ISSUE THREAD

**Issue by wirelesss** [javadev/underscore-java#70]
Hi,
I found poor performance in **intersection method**,
I propose include this method intersection with better performance (view traditional in output console)

Add new method : **notIntersection:** 
and Change actual intersection method with this:
------------------ Code Example ------------------------------

`import static java.util.Arrays.asList;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.github.underscore.$;

import utils.TiempoEnum;
import utils.UtilsTiempo;

public class TestUnderscore2 {

    public static <T> List<T> intersection(List<T> list1, List<T> list2) {
        List<T> list = new ArrayList<T>();
        for (T t : list1) {
            if(list2.contains(t)) {
                list.add(t);
            }
        }
        return list;
    }
    
    public static <T> List<T> notIntersection(List<T> list1, List<T> list2) {
        List<T> list = new ArrayList<T>();
        for (T t : list1) {
            if(!list2.contains(t)) {
                list.add(t);
            }
        }
        return list;
    }
	public static void main(String[] args){
		Date fecha1;
		Date fecha2;
		List<String> resultado;
		fecha1 = new Date();		
		resultado = $.intersection(asList("101", "2", "1", "10"), asList("2", "1"));
		fecha2 = new Date();
		System.out.println("Diff time ms underscore:");
		System.out.println(fecha2.getTime()-fecha1.getTime());
		System.out.println("result:");
		System.out.println(resultado.toString());
		
		fecha1 = new Date();		
		resultado = intersection(asList("102", "3", "2", "11"), asList("3", "2"));
		fecha2 = new Date();
		System.out.println("Diff time ms traditional:");
		System.out.println(fecha2.getTime()-fecha1.getTime());
		System.out.println("result:");
		System.out.println(resultado.toString());
	}
	
}
`
--------------

**Output Console:**

Diff time ms underscore:
23
result:
[2, 1]
Diff time ms traditional:
0
result:
[3, 2]
------
I hope your comments.

**Comment by javadev** [comment]
@wirelesss Thanks for the code example. I prepared a PR with improvements: https://github.com/javadev/underscore-java/pull/71

**Comment by javadev** [comment]
Improvements were added to master branch 👍
