### ISSUE TITLE
What is the advantage of this library over other APIs?

### ISSUE THREAD

**Issue by bryant1410** [javadev/underscore-java#72]
What is the advantage of this library over the Java 8 Stream API, or over [this backport for Java 6+](https://github.com/aNNiMON/Lightweight-Stream-API)?

**Comment by javadev** [comment]
It allows to write similar code in java and javascript. There are three plugins available math, string and lidash. Xml and json converters are part of string and lodash plugins.

**Comment by javadev** [comment]
I created a library which uses toJson, fromJson and fetch methods. https://github.com/javadev/nazk-client
