### ISSUE TITLE
$.range should return a list?

### ISSUE THREAD

**Issue by linktohack** [javadev/underscore-java#78]
I am trying the library and it is really cool!

I am wondering if there is a similar way I can do something like this? `$.map($.range(10), ...`

Thanks

**Comment by javadev** [comment]
Hi,

Thank yoy for suggestion.
I will try to add array support for map() method.

Regards, Valentyn

**Comment by javadev** [comment]
I added int array parameter for map() method.

This example works for me:

```java
        List<Integer> result = $.map($.range(3), new Function1<Integer, Integer>() {
            public Integer apply(Integer item) {
                return (item + 1) * 3;
            }
        });
        // ->[3, 6, 9]
```

**Comment by linktohack** [comment]
Thanks @javadev for your quick response. Excuse me for reopening this issue, I was not very clear when I said `map`. What about other method like `reduce`? Or we have to pass the range through a `map` first?

**Comment by javadev** [comment]
`reduce` supports only collections as I know. I may add int array support for `reduce` if you wish.

**Comment by linktohack** [comment]
I wish to have a generic way but yes, I would love to have `reduce` (and `chain` if possible)

Thanks again @javadev. Great lib!

**Comment by javadev** [comment]
Added `int[]` argument support for `reduce` and `chain`.

**Comment by javadev** [comment]
New version was released today 👍

**Comment by javadev** [comment]
`U.range` returns list of integers since version 1.44.
