### ISSUE TITLE
Why implement own Optional

### ISSUE THREAD

**Issue by markgeek** [javadev/underscore-java#86]
why not use java's own Optional

**Comment by javadev** [comment]
This library is for jdk 6+. I need store nulls inside Optional.

**Comment by javadev** [comment]
Underscore-java is the minimum java version is 8 now. It may be replaced with java Optional.

**Comment by javadev** [comment]
Underscore-java is the minimum java version is 11 now.

**Comment by javadev** [comment]
The java.util.Optional replaced the custom Optional.
