### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by samczsun** [javadev/underscore-java#89]
Hi,

I just stumbled across this project and I noticed that you've violated the licenses of several projects by blatantly copy/pasting code into your own project and changing a few identifiers. While your license (MIT) is compatible with some of the projects you've copied, you've still claimed copyright of code which you don't own copyright to.

Fava (Unlicensed):
https://github.com/javadev/underscore-java/blob/6334e31bfe7cde647bf16af6b21858bc28965d0b/math-plugin/src/main/java/com/github/underscore/math/%24.java#L74-L130
https://github.com/donnior/fava/blob/master/src/main/java/org/agilej/fava/util/Numbers.java#L8-L66

Apache Chemistry OpenCMIS (APL v2.0)
https://github.com/javadev/underscore-java/blob/master/string-plugin/src/main/java/com/github/underscore/string/%24.java#L1094-L1140
https://github.com/apache/chemistry-opencmis/blob/trunk/chemistry-opencmis-commons/chemistry-opencmis-commons-impl/src/main/java/org/apache/chemistry/opencmis/commons/impl/json/JSONValue.java#L107-L175

https://github.com/javadev/underscore-java/blob/master/string-plugin/src/main/java/com/github/underscore/string/%24.java#L1151-L1196
https://github.com/apache/chemistry-opencmis/blob/trunk/chemistry-opencmis-commons/chemistry-opencmis-commons-impl/src/main/java/org/apache/chemistry/opencmis/commons/impl/json/JSONValue.java#L293-L337

minimal-json (EPL v1.0):
https://github.com/javadev/underscore-java/blob/master/string-plugin/src/main/java/com/github/underscore/string/%24.java#L1638-L1979
https://github.com/mirego/minimal-json/blob/master/src/main/java/com/eclipsesource/json/JsonParser.java#L99-L497

Java itself (GPL v2):
https://github.com/javadev/underscore-java/blob/master/src/main/java/com/github/underscore/Optional.java
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/util/Optional.java

Why not simply depend on these projects instead of violating their respective licenses? For example, the [EPL states that](http://www.eclipse.org/legal/epl-v10.html)
```"Contributor" means any person or entity that distributes the Program.```
and that
```
When the Program is made available in source code form:

a) it must be made available under this Agreement; and
b) a copy of this Agreement must be included with each copy of the Program.
Contributors may not remove or alter any copyright notices contained within the Program.
```

**Comment by javadev** [comment]
Nice issue.
Thanks for links.
