### ISSUE TITLE
Documentation ambiguity

### ISSUE THREAD

**Issue by jaimeagudo** [javadev/underscore-java#90]
First of all thanks for sharing! 👍 

Just thinking out loud: it would be great if the examples like the `map` would be clearer
```java
$.map(asList(1, 2, 3), new Function1<Integer, Integer>() {
    public Integer apply(Integer item) {
        return item * 3;
    }
});
```

For example, may I return an array of Strings or Booleans? May I access the index of the iterator like in js?

The following use case doesn't compile

```java
  static String[] getCheckedIems(String[] allItems, final CharSequence[] items) {

        final List<CharSequence> listItems = Arrays.asList(items);
        return $.map(Arrays.asList(allItems), new Function1<String, Integer>() {
            public String apply(String item) {
                return listItems.contains(item) ? item : null;
            }
        });
    }
```

**Comment by javadev** [comment]
You may return list of strings and convert it to array. There is no index in map callback.
